### ISSUE TITLE
TODO-test

### ISSUE THREAD

**Issue by mat-sop** [Team4stud/App#2]
###### TODO
- [x] zmienić typ pola w klasie Frame z Rectangle2D na Rect (org.opencv.core.Rect) - z tego co widzę yolo zwraca odrazu ten typ więc nie trzeba będzie robić żadnych konwersji, możliwe że trzeba wtedy lekko przerobić Analizer
- [x] w klasie Frame dodać metodę drawBounds która poprostu nakłada zapisany prostokąt na obrazek i go zwraca, w obiekcie zostaje niezmieniona klatka
- [x] przenieść Classifier do oddzielnego pakietu/folderu
- [x] w Classifier.processFrame usunąć rysowanie prostokątów, obsłużyć sytuację jeżeli znajdzie kilka obiektów (np. wybrać ten o największej pewności)
- [ ] sprawdzić obsługę przypadków typu: nie wykryto żadnego obiektu, nie wczytano klatki z dysku itp.
- [ ] znaleźć przykładowy filmik na którym będzie tylko 1 szukany obiekt -> np. 1 osoba
- [ ] dodanie jakiejś walidacji wybranego pliku, przypadek gdy użytkownik wybierze plik który nie jest plikiem video
- [x] dodać wywołania yolo i analizera do controllera (dopiero jak będzie wszystko gotowe z anallizerem, frame i classifier)
- [x] (dopiero jak będą gotowe pozostałe moduły) wyświetlanie informacji pobranych z klatki -> usunięcie losowych prostokątów i prawo/lewo/góra/dół zastąpić wartościami x, y
